# Generated by Django 4.2.30 on 2026-06-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('installment', 'Installment'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='cars.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='customers.customer')),
            ],
        ),
    ]
